const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

/**
 * Input swagger.json generated by the backend.
 */
const inputFile = path.join(__dirname, "../swagger.json");

/**
 * Temporary folders used during generation.
 */
const outputDirSwagger = path.join(__dirname, "../src/app/generated/swagger");
const outputDirNswag = path.join(__dirname, "../src/app/generated/nswag");

/**
 * Final destination of generated Angular clients.
 */
const outputDirClients = path.join(__dirname, "../src/app/api");

/**
 * NSwag template used to generate one .nswag file per service.
 */
const template = fs.readFileSync(
  path.join(__dirname, "../templates/client.nswag.json"),
  "utf8"
);

/**
 * Create required directories if they do not exist.
 */
if (!fs.existsSync(outputDirSwagger)) {
  fs.mkdirSync(outputDirSwagger, { recursive: true });
}

if (!fs.existsSync(outputDirNswag)) {
  fs.mkdirSync(outputDirNswag, { recursive: true });
}

if (!fs.existsSync(outputDirClients)) {
  fs.mkdirSync(outputDirClients, { recursive: true });
}

/**
 * Load the original swagger document.
 */
const swagger = JSON.parse(fs.readFileSync(inputFile, "utf8"));

/**
 * Match controller name from paths like:
 *
 * /api/Service/Account/Login
 * /api/Service/AccountCode/GetAll
 */
const PREFIX_REGEX = /^\/api\/Service\/([^\/]+)/;

/**
 * Object that will contain grouped endpoints.
 *
 * Example:
 *
 * {
 *   Account: {
 *      "/api/Service/Account/Login": {...},
 *      "/api/Service/Account/RefreshToken": {...}
 *   },
 *   AccountCode: {
 *      ...
 *   }
 * }
 */
const groups = {};

/**
 * Group swagger endpoints by controller/service name.
 */
for (const route of Object.keys(swagger.paths)) {

  const match = route.match(PREFIX_REGEX);

  if (!match)
    continue;

  const group = match[1];

  groups[group] ??= {};

  groups[group][route] = swagger.paths[route];
}

/**
 * Recursively search an object for every "$ref".
 *
 * Example:
 *
 * LoginVm
 *      ↓
 * UserDto
 *      ↓
 * RoleDto
 *
 * returns:
 *
 * LoginVm
 * UserDto
 * RoleDto
 */
function collectRefs(obj, refs = new Set()) {

  if (!obj)
    return refs;

  if (Array.isArray(obj)) {

    obj.forEach(x => collectRefs(x, refs));

    return refs;
  }

  if (typeof obj !== "object")
    return refs;

  if (obj.$ref) {

    const name = obj.$ref.split("/").pop();

    refs.add(name);
  }

  for (const value of Object.values(obj))
    collectRefs(value, refs);

  return refs;
}

/**
 * Starting from the root DTOs used by an endpoint,
 * recursively resolve every referenced schema.
 *
 * This guarantees that generated swagger files contain
 * every DTO needed by NSwag.
 */
function resolveSchemas(refs, allSchemas) {

  const collected = {};

  const visited = new Set();

  function visit(schemaName) {

    if (visited.has(schemaName))
      return;

    visited.add(schemaName);

    const schema = allSchemas[schemaName];

    if (!schema)
      return;

    collected[schemaName] = schema;

    const nested = collectRefs(schema);

    nested.forEach(visit);
  }

  refs.forEach(visit);

  return collected;
}

/**
 * Generate one swagger.json and one .nswag.json
 * for each controller/service.
 */
for (const [groupName, paths] of Object.entries(groups)) {

  /**
   * Collect all DTOs referenced by the endpoints.
   */
  const refs = new Set();

  Object.values(paths).forEach(pathItem => collectRefs(pathItem, refs));

  /**
   * Resolve nested DTO dependencies.
   */
  const schemas = resolveSchemas(
    refs,
    swagger.components.schemas
  );

  /**
   * Build a new swagger document that contains only:
   *  - current controller endpoints
   *  - required DTOs
   *  - security definitions
   */
  const result = {
    openapi: swagger.openapi,
    info: {
      ...swagger.info,
      title: `${swagger.info.title} - ${groupName}`
    },
    paths,
    components: {
      schemas,
      securitySchemes: swagger.components.securitySchemes
    },
    security: swagger.security
  };

  /**
   * Convert PascalCase to kebab-case.
   *
   * AccountNatureType
   *      ↓
   * account-nature-type
   */
  const kebab = groupName
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase();

  /**
   * Save generated swagger document.
   */
  const filename = `${kebab}.swagger.json`;

  fs.writeFileSync(
    path.join(outputDirSwagger, filename),
    JSON.stringify(result, null, 2)
  );

  console.log(`Generated ${filename}`);

  /**
   * Create an NSwag configuration for this swagger file.
   */
  const nswag = template
    .replace(
      "__SWAGGER__",
      `../../../../src/app/generated/swagger/${kebab}.swagger.json`
    )
    .replace(
      "__OUTPUT__",
      `../../../../src/app/api/${kebab}/${kebab}.client.ts`
    );

  /**
   * Save NSwag configuration.
   */
  fs.writeFileSync(
    path.join(outputDirNswag, `${kebab}.nswag.json`),
    nswag
  );
}

/**
 * Execute NSwag for every generated configuration.
 *
 * This generates Angular client files.
 */
const files = fs
  .readdirSync(outputDirNswag)
  .filter(f => f.endsWith(".nswag.json"))
  .sort();

for (const file of files) {

  console.log(`Running ${file}...`);

  execSync(
    `nswag run "${path.join(outputDirNswag, file)}"`,
    {
      stdio: "inherit"
    }
  );
}

/**
 * Remove a directory recursively.
 */
function deleteDirectory(dir) {

  if (!fs.existsSync(dir))
    return;

  fs.rmSync(dir, {
    recursive: true,
    force: true
  });
}

// Remove all temporary generation artifacts.
deleteDirectory(path.join(__dirname, "../src/app/generated"));

console.log("Temporary files removed.");
